###########################
#  Configuración global.  #
###########################
option domain-name-servers 172.17.5.11, 172.17.5.12;
default-lease-time 86400;



#########################
#  Declaraciones host   #
#########################

host cliente2 {
  hardware ethernet aa:aa:aa:aa:aa:03;
  fixed-address 172.17.4.14;
}

host cliente1 {
  hardware ethernet aa:aa:aa:aa:aa:02;
  fixed-address 172.17.5.101;
}



###########
#  (DMZ)  #
###########

subnet 172.17.4.0 netmask 255.255.255.0 {
  range 172.17.4.20 172.17.4.250;
  option routers 172.17.4.10;
  max-lease-time 604800;
}



##########
#  (MZ)  #
##########

subnet 172.17.5.0 netmask 255.255.255.0 {
  range 172.17.5.20 172.17.5.250;
  option routers 172.17.5.10;
  max-lease-time 172800;
}
