###########################
#  Configuración global.  #
###########################

# Tiempo predeterminado de lease.

default-lease-time 3600;

#Tiempo máximo de lease.

max-lease-time 86400;

######################
#  Primera red (MZ)  #
######################

subnet 172.17.5.0 netmask 255.255.255.0 {
  range 172.17.5.100 172.17.5.200;
  option routers 172.17.5.11;
  option domain-name-servers 8.8.8.8, 8.8.4.4;
}
